name: Deploy to Replicate
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Cog
        uses: replicate/setup-cog@v1
      - name: Deploy to Replicate
        run: cog push r8.im/aiaprendefacil-hugo/meu-modelo-imagens
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}